### ISSUE TITLE
Code coverage report doesn't appear to line up with ts files

### ISSUE THREAD

**Issue by robmcm** [kozlice/angular2-webpack-boilerplate#3] opened 2016-10-18 12:50 UTC
When looking at the generated code coverage report, it loads the ts files, but the hilighting and reporting numbers (lines, statements etc) appear to be based from the original JS.

![image](https://cloud.githubusercontent.com/assets/336909/19478212/8ba56ee0-9539-11e6-8f23-d2c70476d58e.png)

![image](https://cloud.githubusercontent.com/assets/336909/19478236/af3063c4-9539-11e6-90c6-58cd1d5e6f0f.png)

Is this the same for your build?

**Comment by kozlice** [comment] 2016-10-19 08:18
@robmcm I'll take a look, thanks for noticing. I need to catch up with recent release of TypeScript and see if `require` can be replaced with `import` (it didn't work with non-`.ts` files at the time I wrote this).

**Comment by robmcm** [comment] 2016-10-19 08:27
I am not sure it ever worked (on any project), if you search for ts coverage in google images, all the examples seem to be a little off.

On a side note I also had to disable the linting on a vanilla install to get it to run.

Thanks for your work.

**Comment by kozlice** [comment] 2016-10-19 08:37
@robmcm I'll check that too, thanks. Most likely it's loose dependency version problem – `^` is used a lot in `package.json`, and stuff in Node world tends to break even with minor releases. I guess I'd better freeze them to exact version.

**Comment by robmcm** [comment] 2016-10-19 08:58
@kozlice Yeah, but these dependencies are moving quite quickly, would be good to keep up until they stabilize. Perhaps updating manually rather than with ^ would be safer though :)

**Comment by robmcm** [comment] 2016-10-27 13:49
@kozlice On a recent update it appears to be working again (when I remove the lint step), but I suppose it could break again in the future with non locked down version ;)

**Comment by kozlice** [comment] 2016-10-27 15:58
@robmcm I've been checking this yesterday and couldn't reproduce as well. Will close the issue once I'll push `package.json` with fixed versions. Thanks for your help!

**Comment by robmcm** [comment] 2016-10-27 16:08
@kozlice Thanks for your help, this project has been invaluable!

**Closed as completed** 2016-11-11 16:15 UTC
